# -*- coding: utf-8 -*-
import random

quotes = [
    'El Sabio no tiene intereses propios, hace suyos los intereses del pueblo.',
    'He decidido hacer lo que me gusta porque es bueno para la salud.',
    '¿Cuál es el eslabón más débil de la cadena de seguridad en sistemas informáticos?. El usuario final.',
    'Utilizamos Open Source en nuestros servidores porque es una manera más de controlar nuestro propio destino. By DiBona (Google Admin)',
    'Amar es borrar el Windows del disco de ella.',
    'Bienaventurados los Pesimistas. Por que hacen BACKUPS.',
    'En un principio el Universo por nosotros conocido, fue una versión beta.',
    'Dios es real (a no ser que esté declarado como integer).',
    'Algún día seré capaz de decirte que no te arreglo la computadora !!!',
    'Si no consigues encontrar el problema, seguro es el BIOS (Bichito Ignorante Operando Sistema).',
    'Computadora que es un carro, ¿Tiene un burro adelante?',
    'Si el Universo fuera un programa estaría hecho en C y correría sobre un sistema GNU/LINUX.',
    'Mouse no encontrado. ¿Usted tiene gato? (S/N)',
    'Si su Windows no le da problemas. ¡Reclame a Microsoft!',
    'HardWare: Todo Aquel Artefacto que Resive Nuestros Golpes y SoftWare de código cerrado: La Causa.',
    'Si debbuging es el proceso de eliminar errores, entonces la programación debe ser el proceso de crearlos.',
    'Hay dos formas de escribir programas sin errores. Sólo la tercera funciona.',
    'Amante: Versión shareware de esposa.',
    'Programa de código cerrado de una computadora: Extraña forma de vida que tiene la capacidad de transformar comandos en mensajes de error.',
    'Hay tontos que tontos parecen, hay tontos que tontos son, pero hay una clase peor de tontos que hacen parecer tontos a los que listos son.',
    'En un mundo sin fronteras, ¿quien necesita puertas y ventanas?',
    'El software libre es como el sexo, es mejor cuando es gratis.',
    'Paz, Amor y Compilación del kernel.',
    'Windows : El único virus que soporta y daña todo tu trabajo (no importa la versión).',
    'Antes ciego que con vista.',
    'Linux, el sistema operativo todoterreno!',
    'Aunque no lo crean existe M$ Linux, este nuevo OS esta basado en la una nueva licencia GPL(Gates Private License).',
    'Sabes que es amor cuando memorizas su numero de IP para saltar el DNS.',
    'Quien fuera programador para meterte una sentecia por SQL.',
    'Los errores poseen su valor, aunque sólo en alguna ocasión.',
    'La tecnología cambia, el talento no tanto.',
    'Dios perdona, Yo No. Khaleesi.',
    'El dinero no hace la felicidad, pero yo prefiero llorar en una ferrari.',
    'Ustedes son como Windows, cuando no saben que hacer se cuelgan y tengo que poner control + alt + del',
    'En un principio estaba el software propietario. Y se ideó el software libre, Algunos se quejaron porque era poco potente. Y se desarrollaron todas las herramientas GNU, Algunos se quejaron porque faltaba un núcleo. Y apareció Linux, Algunos se quejaron porque no era portable. Y se portó a decenas de arquitecturas, Algunos se quejaron porque no había soporte hardware. Y se programaron los drivers, Algunos se quejaron porque no había soporte. Y se fundaron Debian,Red Hat, SuSE, etcétera, Algunos se quejaron porque no era rentable. Y aparecieron las certificaciones y los planes de soporte basados en servicios, Algunos se quejaron porque era difícil. Y se desarrollaron Gnome y KDE, Algunos se quejaron porque había pocas aplicaciones. Y se programaron más de . aplicaciones en los repositorios públicos, Algunos se quejaron porque era lento. Y apareció el núcleo ., Algunos se quejaron porque no había compatibilidad. Y se programaron Wine y Cedega, Algunos se quejaron porque era feo. Y apareció Beryl, Entonces, ¿cuál será la próxima excusa para no usar software libre?',
    'Un programador es un mamífero nocturno de ojos rojos capaz de conversar con objetos inanimados.',
    'Los programadores de verdad no documentan sus programas. Si es difícil de codificar que sea difícil de entender.',
    'Todas las computadoras que usan Windows esperan a la misma velocidad y las que usan GNU/Linux acaban sus procesos más rápido.',
    'Quién será el tal General Failure y por qué estará leyendo el disco duro? (del mensaje de error "General Failure reading disk C:")',
    '¿Sabes cuál es el secreto de Windows? Yo tampoco.',
    'El ordenador ha sido hasta ahora el producto más genial de la vagancia humana (slogan de IBM)',
    'Gran oferta: Hoy, con Windows XP regalamos dos botones de reset de repuesto.',
    'Instala Windows XP ó Vista ó dígase la versión que sea y que la fuerza te acompañe.',
    'La diferencia entre WindowsXP y un virus, es que el virus es gratis.',
    'Windows XP es Multitarea: está preparado para que varios programas fallen simultáneamente.',
    'Los README son para los cobardes. Sé valiente. Ejecuta el programa.',
    'Una imagen vale más que mil palabras. Pero ocupa mucho más memoria.',
    'Imaginan una versión de Windows que anuncie? "Ahora sin nuevas funcionalidades, ¡pero corre en el PC que ya tienes, consume la mitad de memoria, un cuarto de disco, !y no se cae!". Sí lo se, soñar es absolutamente gratis.',
    'Me gustaría cambiar el mundo, pero no me dan el codigo fuente.',
    'La programación es una carrera entre ingenieros tratando de hacer mejores y mas grandes programas resistentes a idiotas y el universo haciendo mejores y más grandes idiotas. Por ahora gana el universo.',
    'Mi software nunca tiene fallos, simplemente desarrolla características aleatorias.',
    'Las rosas son #ffa5f5 las violetas son #ad00bd.',
    'Abriste un editor de imágenes o creaste un archivo html y pusiste estos valores para comprobar que efectivamente fueran esos los colores.',
    'Solo hay 10 tipos de personas: las que saben binario y las que no.',
    'Si no lo consigues a la primera, llámalo versión 1.0.',
    'Microsoft: Ustedes tenenen las preguntas, nosotros los clips que bailan.',
    'No soy antisocial; Soy de interfaz poco amigable.',
    'Una computadora con Windows te deja cometer equivocaciones más rápido que cualquier invento en la historia humana - con las excepciones posibles de armas de mano y del tequila.',
    'Mi software no tiene bugs. Solamente desarrolla características al azar.',
]

def random_quote():
    return quotes[random.randrange(0, len(quotes))]

